---
title: "East vs West 201402"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

<!--
### Data Read in

동과 서의 차이에 대한 응답지 읽어들이기

```{r, echo = FALSE}
east.west1402 <- read.table("../data/east_west1402.txt", header = TRUE, stringsAsFactors = FALSE)
str(east.west1402)
```

필요한 `chr` 오브젝트들을 `factor`로 변환

```{r, echo = FALSE}
east.west.2 <- east.west1402
east.west.2$sex <- factor(east.west.2$sex, levels=c("남", "여"))
str(east.west.2)
```

지역 관련 요인을 '수도권'과 '지방'으로 크게 구분

```{r, echo = FALSE}
east.west.2$region <- factor(east.west.2$region, levels = c("서울", "경기","인천", "대구", "광주", "울산", "강원", "경상", "몽골"))
str(east.west.2)
east.west.2$region.2 <- factor(ifelse(east.west.2$region %in% c("서울", "경기", "인천"), "수도권", "지방"), levels = c("수도권", "지방"))
str(east.west.2)
```

학번을 크게 '13학번 이후', '12학번 이전'과 '12학번 이후', '11학번 이전'으로 크게 구분.

```{r, echo = FALSE}
east.west.2$year<-factor(ifelse(east.west.2$year.entrance %in% c(2013, 2014), "Younger", "Older"), levels=c("Younger", "Older"), labels=c("13학번 이후", "12학번 이전"))
east.west.2$year.2<-factor(ifelse(east.west.2$year.entrance %in% c(2012, 2013, 2014), "Younger", "Older"), levels=c("Younger", "Older"), labels=c("12학번 이후", "11학번 이전"))
str(east.west.2)
```

각 질문의 응답을 한글로 쉽게 파악하도록 변환

```{r, echo = FALSE}
east.west.2$monkey<-factor(east.west.2$Q_1, levels=1:3, labels=c("원숭이-바나나", "원숭이-팬더", "팬더-바나나"))
east.west.2$leader<-factor(east.west.2$Q_2, levels=1:2, labels=c("여전히 행복하다", "행복하지 않다"))
east.west.2$saucer<-factor(east.west.2$Q_3, levels=1:3, labels=c("맨 위", "중간", "맨 아래"))
```

계산이 좀 편하도록 `east.west.2`를 검색 목록에 올림. 소수이하 자릿수 조정

```{r, echo = FALSE}
attach(east.west.2)
options(digits=2)
```
-->

### 동과 서

```{r, east and west}
kable(t(as.matrix(table(monkey), 1)))
kable(t(as.matrix(table(leader), 1)))
kable(t(as.matrix(table(saucer), 1)))
kable(table(saucer, monkey))
```

원숭이-바나나-팬더 질문에 대하여 성별, 출신지역별, 학번별 차이 확인. 주변합과 주변분포를 함께 표시

```{r, xtab}
source("./addmargins_kr.R")
tbl.m.sex <- table("성별" = sex, "둘을 묶으면?" = monkey)
tbl.m.sex.a <- addmargins.kr(tbl.m.sex)
pander(tbl.m.sex.a)
pander(matrix(paste(format(prop.table(tbl.m.sex, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.m.sex)[1], dimnames = dimnames(tbl.m.sex)))
tbl.m.region <- table("지역" = region.2, "둘을 묶으면?" = monkey)
tbl.m.region.a <- addmargins.kr(tbl.m.region)
pander(tbl.m.region.a)
pander(matrix(paste(format(prop.table(tbl.m.region, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.m.region)[1], dimnames = dimnames(tbl.m.region)))
tbl.m.year <- table("학번" = year, "둘을 묶으면?" = monkey)
tbl.m.year.a <- addmargins.kr(tbl.m.year)
pander(tbl.m.year.a)
pander(matrix(paste(format(prop.table(tbl.m.year, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.m.year)[1], dimnames = dimnames(tbl.m.year)))
tbl.m.year.2 <- table("학번" = year.2, "둘을 묶으면?" = monkey)
tbl.m.year.2.a <- addmargins.kr(tbl.m.year.2)
pander(tbl.m.year.2.a)
pander(matrix(paste(format(prop.table(tbl.m.year.2, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.m.year.2)[1], dimnames = dimnames(tbl.m.year.2)))
```

여전히 행복한가요? 질문에 대하여 성별, 지역별, 학번별 차이 확인.

```{r, still happy}
tbl.l.sex <- table("성별" = sex, "여전히 행복한가요?" = leader)
tbl.l.sex.a <- addmargins.kr(tbl.l.sex)
pander(tbl.l.sex.a)
pander(matrix(paste(format(prop.table(tbl.l.sex, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.l.sex)[1], dimnames = dimnames(tbl.l.sex)))
tbl.l.region <- table("지역" = region.2, "여전히 행복한가요?" = leader)
tbl.l.region.a <- addmargins.kr(tbl.l.region)
pander(tbl.l.region.a)
pander(matrix(paste(format(prop.table(tbl.l.region, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.l.region)[1], dimnames = dimnames(tbl.l.region)))
tbl.l.year <- table("학번" = year, "여전히 행복한가요?" = leader)
tbl.l.year.a <- addmargins.kr(tbl.l.year)
pander(tbl.l.year.a)
pander(matrix(paste(format(prop.table(tbl.l.year, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.l.year)[1], dimnames = dimnames(tbl.l.year)))
tbl.l.year.2 <- table("학번" = year.2, "여전히 행복한가요?" = leader)
tbl.l.year.2.a <- addmargins.kr(tbl.l.year.2)
pander(tbl.l.year.2.a)
pander(matrix(paste(format(prop.table(tbl.l.year.2, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.l.year.2)[1], dimnames = dimnames(tbl.l.year.2)))
```

어느 것이 앞에 있나요? 질문에 대하여 성별, 지역별, 학번별 차이 확인.

```{r, saucer}
tbl.s.sex <- table("성별" = sex, "어느 것이 앞에 있나요?" = saucer)
tbl.s.sex.a <- addmargins.kr(tbl.s.sex)
pander(tbl.s.sex.a)
pander(matrix(paste(format(prop.table(tbl.s.sex, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.s.sex)[1], dimnames = dimnames(tbl.s.sex)))
tbl.s.region <- table("지역" = region.2, "어느 것이 앞에 있나요?" = saucer)
tbl.s.region.a <- addmargins.kr(tbl.s.region)
pander(tbl.s.region.a)
pander(matrix(paste(format(prop.table(tbl.s.region, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.s.region)[1], dimnames = dimnames(tbl.s.region)))
tbl.s.year <- table("학번" = year, "어느 것이 앞에 있나요?" = saucer)
tbl.s.year.a <- addmargins.kr(tbl.s.year)
pander(tbl.s.year.a)
pander(matrix(paste(format(prop.table(tbl.s.year, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.s.year)[1], dimnames = dimnames(tbl.s.year)))
tbl.s.year.2 <- table("학번" = year.2, "어느 것이 앞에 있나요?" = saucer)
tbl.s.year.2.a <- addmargins.kr(tbl.s.year.2)
pander(tbl.s.year.2.a)
pander(matrix(paste(format(prop.table(tbl.s.year.2, margin = 1)*100, digits = 2, nsmall = 1), "%", sep = ""), nrow = dim(tbl.s.year.2)[1], dimnames = dimnames(tbl.s.year.2)))
```

## Save

```{r, save, echo = FALSE}
save.image("./east_west1402.RData")
```
